version: '3.9'
services:
  backend:
    build: /backend
    ports:
      - 8000:3001
    volumes:
      - .:/backend/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /db/data:/var/lib/mysql
  frontend:
    build: /frontend
    ports:
      - 3000:3000
    volumes:
      - .:/frontend/app
